enable Summarizer with OAP
oap-project/oap-mllib pull request #144
Opened 2021-11-15 10:08 UTC by minmingzhu

1. enable Summarizer CPU and GPU with one API
2. add Summarizer example

2021-11-22 02:17 UTC, xwu99 requested changes
Pls rebase to master as there has been some large refactor.

2021-11-22 02:17 UTC, xwu99 commented on mllib-dal/src/spark-3.1.1/main/scala/org/apache/spark/mllib/stat/Statistics.scala
> +  def kolmogorovSmirnovTest(
```suggestion
  def kolmogorovSmirnovTest(data: JavaDoubleRDD,
```
should format like this

2021-11-24 04:37 UTC, xwu99 requested changes

2021-11-24 04:37 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/stat/SummarizerDALImpl.scala
> +        val meanMatrix = OneDAL.numericTableToOldMatrix(OneDAL.makeNumericTable(result.meanNumericTable))
The code is not decent here to convert twice. 
There is a logical problem in the function numericTableToOldMatrix. isTransposed should be set to true. This function is not used, you can remove it. 
Is result.meanNumericTable a Nx1 or 1xN matrix? For Nx1, You can call numericTableNx1ToVector, For 1xN, you can modify numericTableNx1ToVector function to numericTable1xNToVector.

2021-11-24 04:37 UTC, xwu99 commented on mllib-dal/src/main/scala/org/apache/spark/mllib/stat/spark320/Statistics.scala
> +class Statistics extends SummarizerShim{
```suggestion
class Statistics extends SummarizerShim {
```

2021-11-24 04:37 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/stat/SummarizerShim.scala
> +import org.apache.spark.mllib.stat.spark320.{Statistics => SummarizerSpark320 }
better to use Statistics => StatisticsSpark320

2021-11-24 04:42 UTC, xwu99 commented on mllib-dal/src/main/scala/org/apache/spark/mllib/stat/spark320/Statistics.scala
> +class Statistics extends SummarizerShim{
something wrong with CI, pls make sure you didn't mess up other algos.  Only change what you need to change. Pls compare the changed files for 3.1.1, 3.1.2 and 3.2 to see anything inconsistent.

2021-11-24 04:53 UTC, xwu99 commented on dev/codestyle/.clang-format
>  Language:        Cpp
for code format change, you just need to format your changes.

2021-11-24 04:53 UTC, xwu99 commented on dev/codestyle/.clang-format
>  Language:        Cpp
for code format change, you just need to format your changes.

2021-11-26 03:42 UTC, xwu99 requested changes

2021-11-29 02:44 UTC, minmingzhu commented
> Thanks for opening a pull request!
> 
> Could you open an issue for this pull request on Github Issues? https://github.com/oap-project/oap-mllib/issues
> 
> Then could you also rename _**pull request title**_ and _**commit log**_ in the following format?
> 
> ```
> [ML-${ISSUES_ID}] ${detailed message}
> ```
> 
> See also:
> 
> * [Other pull requests](https://github.com/oap-project/oap-mllib/pulls/)

2021-11-29 02:44 UTC, minmingzhu commented
#151

2021-11-29 02:59 UTC, minmingzhu commented
#153

2021-11-29 05:15 UTC, merged

2021-11-29 05:15 UTC, xwu99 commented
@minmingzhu thanks for your work. Merged!