[ML-248][LinearRegression] Add Linear Regression algorithm
oap-project/oap-mllib pull request #261
Opened 2023-04-04 04:56 UTC by argentea

Add Linear regression feature.

2023-04-04 05:22 UTC, xwu99 commented on dev/prepare-build-deps-gpu.sh
Could you work with @minmingzhu to merge the version changes in build scripts to #259

2023-04-07 02:44 UTC, carsonwang commented on mllib-dal/src/main/native/LinearRegressionDALImpl.cpp
> +Java_com_intel_oap_mllib_regression_KMeansDALImpl_cLROneapiCompute(
A lot of code copied from KMeans. Please update and clean up.

2023-05-04 06:56 UTC, xwu99 requested changes

2023-05-04 06:56 UTC, xwu99 commented on examples/linear-regression/run.sh
Please follow kmeans example, some changes for run.sh and need to create a new script named "run-gpu-standalone.sh".

2023-05-04 06:56 UTC, xwu99 commented on examples/linear-regression/src/main/scala/org/apache/spark/examples/ml/LinearRegressionExample.scala
> +      .load(params.input).toDF("label", "features").repartition(4)
don't use repartition in user code, you should check if partition is enough and change in oap mllib code.

2023-05-04 06:56 UTC, xwu99 commented on examples/linear-regression/src/main/scala/org/apache/spark/examples/ml/LinearRegressionExample.scala
> +        case Row(label:Double,feature:Vector)=>new LabeledPoint(label,feature.toDense)
pay attention to code style. extra space after ","

2023-05-04 06:56 UTC, xwu99 commented on mllib-dal/src/main/native/LinearRegressionDALImpl.cpp
> +#endif
compile error here due to some changes to the include logic, you need to include Common.hpp, pls follow KMeansImpl.cpp

2023-05-04 06:56 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/regression/LinearRegressionDALImpl.scala
> +            println(labeledPoints.select(labelCol).count())
no debug code please.

2023-05-04 06:56 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/regression/LinearRegressionDALImpl.scala
> +      println(useDevice)
no debug code

2023-05-04 06:56 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/regression/LinearRegressionDALImpl.scala
rename filename to LinearRegressionImpl.cpp

2023-05-05 07:08 UTC, argentea commented on mllib-dal/src/main/native/LinearRegressionImpl.cpp
> +                               preview::spmd::communicator<preview::spmd::device_memory_access::usm> comm,
variable name

2023-05-06 07:28 UTC, merged